version: "1.7"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      OWNER_ID: $OWNER_ID
      PING_IMG: $PING_IMG
      START_IMG: $START_IMG
      SUPPORT_CHAT: $SUPPORT_CHAT
      SUPPORT_CHANNEL: $SUPPORT_CHANNEL
      STRING_SESSION: $STRING_SESSION
      SUDO_USERS: $SUDO_USERS
