version: "3.4"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      OWNER_ID: $OWNER_ID
      PING_IMG: $PING_IMG
      DURATION_LIMIT: $DURATION_LIMIT
      SUPPORT_CHAT: $SUPPORT_CHAT
      SUPPORT_CHANNEL: $SUPPORT_CHANNEL
      SESSION: $SESSION
      SUDO_USERS: $SUDO_USERS
